import Script from "next/script";
import Provider from "../components/provider";
import "./globals.css";
import Scripts from "@/components/Scripts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Scripts/>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
